language: php


before_install:
  - curl -s http://getcomposer.org/installer | php -- --install-dir=./bin
  - php ./bin/composer.phar install --dev

php:
  - 5.3
  - 5.4

before_script:
  - wget -nc http://getcomposer.org/composer.phar
  - php composer.phar install --dev

notifications:
  email:
    - travis@bastian-feder.de
